### ISSUE TITLE
Artwork not cached to disk for MPRIS

### ISSUE THREAD

**Issue by olib14** [ludouzi/fooyin#87] opened 2024-05-15 09:59 UTC
Album artwork caching does not create a file for the current track for use with MPRIS, so no artwork is visible in KDE Plasma's Media Player widget. 

`"mpris:artUrl" = [Variant(QString): "file:///home/oliver/.cache/fooyin/covers/MPRISCOVER.jpg"],`

No such file is created, and there are no warnings or debug output.

**Comment by ludouzi** [comment] 2024-05-15 10:11
Strange, it's working fine here. Are you running from master? Does other artwork get cached?

**Comment by olib14** [comment] 2024-05-15 10:13
From master, yep, and artwork appears as expected in the application itself - it just isn't saved to disk (i.e. there is no MPRISCOVER.jpg file).

**Comment by ludouzi** [comment] 2024-05-15 10:58
I'm guessing the artwork isn't embedded? I've just been able to reproduce this for directory artwork. 

Only embedded artwork is extracted and saved as a thumbnail in the disk cache, but MPRIS is still expecting it there. I'll have a fix out in a bit.

**Comment by LukeZBaker** [comment] 2024-05-16 11:14
I don't think browser artwork is fixed where artwork is not embedded. 

For many albums, a cached (but not the right) album art cover is being shown when navigating around the filesystem. Restart the app and the correct artwork is shown, but navigating to a different album often again shows a cached (wrong) album cover.

**Comment by ludouzi** [comment] 2024-05-16 11:47
When you say wrong cover, do you mean it's the cover of a different album, or the right album but wrong resolution?

**Comment by LukeZBaker** [comment] 2024-05-16 11:50
Sorry for not being clear. I mean it's the cover of a different album (a previously viewed album cover).

**Comment by ludouzi** [comment] 2024-05-16 12:26
Exactly. On a fresh run, the in-memory cache is empty and the first album cover is read and saved to the cache. When playing the next album, if the key (generated from a files tags) is the same, it will see the previous cover in the cache already and use it.

I'll investigate another method of generating the key to test this.

**Comment by ludouzi** [comment] 2024-05-16 14:46
With commit 0b6b0fbc4ab87fa2798af636f7038364b494ea46, I've adjusted how a track's album hash (used for the cache key) is generated by using the parent directory if there's no album tag. If that doesn't fix it, the issue lies somewhere else.

**Comment by LukeZBaker** [comment] 2024-05-16 15:03
Looks like its fixed with that commit, thanks!

**Closed** 2024-05-16 15:22 UTC
