### ISSUE TITLE
Duplicated track entries to playlist

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#44] opened 2024-02-08 08:43 UTC
This is with Ubuntu 23.10

With the Simple or Visual layouts, when an album is added to the playlist, each track is duplicated.

**Comment by ludouzi** [comment] 2024-02-08 10:57
How are you adding to the playlist? Through the right-click menu of the library tree widget, or drag-drop?

**Comment by LukeZBaker** [comment] 2024-02-08 10:59
It happens with the right-click menu of the library tree widget and with a drag-n-drop.

**Comment by ludouzi** [comment] 2024-02-08 11:26
I can't reproduce it under Ubuntu 23.10, but I'll keep testing. Does the issue persist after closing and reopening fooyin?

**Comment by LukeZBaker** [comment] 2024-02-08 11:40
Well it still happens after closing and reopening fooyin.

If I remove all the playlists, it sometimes goes away and tracks are not duplicated when adding to a current playlist or sending to a new playlist.

It doesn't always happen but seems more often with multiple tabs open, including when a Filter Results tab is present.

**Comment by ludouzi** [comment] 2024-02-08 12:02
Just to confirm something, how are the tracks duplicated in the playlist? Are the tracks in an album duplicated next to each other (track 1, track 1, track 2, track 2), or is the entire album duplicated below?

**Comment by LukeZBaker** [comment] 2024-02-08 12:05
They are duplicated 01 01, 02 02, 03 03, 04 04

I can reproduce it consistently by switching between layouts and adding a new playlist in each layout.

**Comment by LukeZBaker** [comment] 2024-02-08 13:25
If I clear all the playlists, restart fooyin and choose Ember, it doesn't duplicate tracks when adding to the current playlist, or sending to a new playlist from Artist or Album.

It starts happening when switching between layouts.

**Comment by ludouzi** [comment] 2024-02-08 13:56
I can't reproduce this despite my best efforts. Is there any chance you could make a screen recording?

**Comment by LukeZBaker** [comment] 2024-02-08 17:47
I added a small video to my updated review which shows the issue.

https://www.linuxlinks.com/fooyin-v037-customisable-music-player/2/

**Comment by ludouzi** [comment] 2024-02-08 20:10
Thanks for the video, it helps a lot to narrow down the potential cause. I still don't get the issue following the exact same steps, but I've just pushed a potential fix you can try.

Failing that, you could enable the track selection option for the status widget. If the reported track count is wrong, that would help with where to look next.

<p>
<img src="https://github.com/ludouzi/fooyin/assets/45490980/6a4096bf-c136-49ea-a2a1-1f6b14eab5d1)" width="30%">
</p>

**Comment by LukeZBaker** [comment] 2024-02-09 08:00
I tried your fix but it doesn't resolve the bug on my system. I will try a virtual environment with a fresh Ubuntu 23.10 and see if it makes any difference.

I had both icon and track selection disabled. With both enabled as per your image, the issue still persists. The track count I listen to moves to 1, and the duplicated track goes to track count 1 too even though it's not played at all.

**Comment by ludouzi** [comment] 2024-02-09 08:38
I mean is the track count correct with the row in the library tree selected.

<img src="https://github.com/ludouzi/fooyin/assets/45490980/a3e439b8-a9db-4e12-a2c6-4c7498796df6)" width="60%">

**Comment by ludouzi** [comment] 2024-02-09 12:34
I've just pushed https://github.com/ludouzi/fooyin/commit/fc2705fb0b7700dd57c4e65b84ae9b8a24afd1c9 which should finally fix this.

**Comment by LukeZBaker** [comment] 2024-02-09 13:04
Yes looks fixed.

Tested for 20 minutes switching layouts while adding albums to current playlist, and sending to new playlists. No duplicates. Thanks!

**Closed** 2024-02-09 13:13 UTC
Labels: bug

**Comment by coding-moding** [comment] 2024-11-15 14:45
The player didn't remove duplicates in general. For instance in case if there is playlists in directory where it searches for files it can add multiple duplicates.
